### PR TITLE
support variables for PyStringNode

### PR DESCRIPTION
**Pull request by kufd**
Hi
I use your library and found it usefull to add variables support for PyStringNode
Because in my case it quite common thing

Also sometimes i need to set variables form different behat contextes so i added new methods for this

### CODE REVIEW

**Comment by rudiedirkx** [comment]
`.idea` should be in your global `.gitignore`, not in this repo's.

PyString is especially useful for multi line text, right? How would you use a multi line variable? Maybe a test should test that. I'd love to see your usecase, to see how it's useful.

**Comment by kufd** [comment]
.gitignore fixed

For PyStringNode i added test into features/simple.feature

In my case i often perform api requests and i need to use variables to create request body
For example:
```
  Scenario: Create some element
    Given set uniqid into variable "uniqid"
    And I send a "POST" request to "/api/v1/elements" with body:
        """
        {
            "username": "<<uniqid>>",
            "email": "<<uniqid>>@example.com",
            "field2": "value"
        }
        """
```

**Comment by rudiedirkx** [comment]
Ooooh, it's about injecting variables into a pystring, not a pystring into a variable. That's a good addition.

**Comment by mkinnovecs** [comment]
Thank you
Could you tell me when you plan to create new release with these changes?

**Comment by rudiedirkx** [comment]
I didn't plan to, but if you need a new release, _now_ seems like a good time.

**Comment by mkinnovecs** [comment]
thank you

**Pull request merged**
